@extends('layouts.main')
@section('content')

<h1>Curriculum</h1>

<div class="panel">
	<div class="row">
	<div class="panel callout radius large-4 small-4 centered columns">
		
		<ul>Table of contents
			<li>Education and training</li>
			<li>Work Experience</li>			
			<li>Skills and competences</li>
			<li>Others</li>
		</ul>
	</div>
	<div class="large-8 small-8 centered columns">
		<div class="panel callout radius">
			<div class="row">
				<div class="large-9 small-9 centered columns">
					<p>
						Hi!</br>
						My name is Carles, in this page you may find an overall of my
						work experience, education as well as some of my skills and competences.

						Feel free to contact me!</li> 
					</p>
				</div>
				<div class="large-3 small-3 centered columns">
					<a href="https://www.linkedin.com/in/carsopre">
						{{HTML::image('assets/imgs/Linkedin-icon.png')}}
					</a>
				</div>
			</div>	
		</div>
	</div>
	</div>
</div>
<div class="subcategory">
	<div class="title-sub">
		<h2> Education and training <h2>
	</div>
<fieldset>
	<legend><h3>Final Project</h3></legend>		
	<div class="title-sec">
			Context-aware systems in well-being. From well-being domain to UML specification.</br>
			Final project done during a 10 month Erasmus-exchange program in Universiteit Twente (Netherlands).		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Background	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			SWELL-COMMIT research project
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Topic	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			In this project is given a solution approach for generating UML models from the well-being domain generated by the SWELL committee.</br>
			This models aim to specify the context, activity and class diagrams of any given application within the well-being domain.
			Furthermore, a study of previous works Is done as well as a specification comparison with ConText toolkit.
			Finally the solution approach proposed is mapped with the SWELL global architecture and with a specific architecture of a SWELL partner, CommonSense.
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			University	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			Universiteit Twente (Netherlands)
		</div>		
	</div>
</fieldset>
<fieldset>
	<legend><h3>Computer Science MsC</h3></legend>		
	<div class="title-sec">
			Computer Science degree. 5 years program		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Principal subjects covered	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			Software Engineering</br>
			Computing Technology</br>
			Information Systems</br>
			Business Information Technology</br>
			Intelligent Systems</br>
			Computing Architecture</br>
			Networking</br>
			Operative Research and Statiscs</br>
		</div>		
	</div>	
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			University	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			Universiteit Twente (Netherlands)
		</div>		
	</div>
</fieldset>
<fieldset>
	<legend><h3>Languages</h3></legend>		
	<div class="title-sec">
		Spanish native speaker.
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			English
		</div>
		<div class="content-row large-9 small-9 columns centered">			
			Certificate in Advanced English - C1 (December 2011)</br>
			TOEFL (Internet-Based Test) - score 97 (December 2012)
		</div>		
	</div>	
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Dutch
		</div>
		<div class="content-row large-9 small-9 columns centered">
			 Univeristeit Twente - Dutch Language Certificate (December 2013)
		</div>		
	</div>
</fieldset>
</div>

<div class="subcategory">
	<div class="title-sub">
		<h2> Work experience <h2>
	</div>
<fieldset>
	<legend><h3>Degestec - Valencia (Spain)</h3></legend>		
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Position
		</div>
		<div class="content-row large-9 small-9 columns centered">
			Web application developer (Assistant).		
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Dates	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			April 2013 - June 2013
		</div>		
	</div>
</fieldset>
<fieldset>
	<legend><h3>F1 Connecting - Valencia (Spain) </h3></legend>		
	<div class="title-sec">
			Thecnical assistance and remote solutions for Carrefour computer system. Servers maintenance.
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Position
		</div>
		<div class="content-row large-9 small-9 columns centered">			
			Technical assistance
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Dates
		</div>
		<div class="content-row large-9 small-9 columns centered">			
			October 2012 - March 2013
		</div>		
	</div>		
</fieldset>	
</div>


<div class="subcategory">
	<div class="title-sub">
		<h2> Skills and competences <h2>
	</div>
<fieldset>
	<legend><h3>Computer skills competences</h3></legend>		
	<div class="title-sec">
			Systems modelling. Unix and Windows software development.
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Programming
		</div>
		<div class="content-row large-9 small-9 columns centered">
			C, C++, Java, Matlab, Mathematica, MIPS, Bash, Clips, Cool, Haskell, Prolog, Python
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Web Development
		</div>
		<div class="content-row large-9 small-9 columns centered">
			HTML, PHP, CSS, JavaScript
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Tools
		</div>
		<div class="content-row large-9 small-9 columns centered">
			OpenERP, Mathematica, Matlab, Eclipse, Office package, OpenIT, Apache.
		</div>		
	</div>
</fieldset>
<fieldset>
	<legend><h3>F1 Connecting - Valencia (Spain) </h3></legend>		
	<div class="title-sec">
			Thecnical assistance and remote solutions for Carrefour computer system. Servers maintenance.
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Position
		</div>
		<div class="content-row large-9 small-9 columns centered">			
			Technical assistance
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Dates
		</div>
		<div class="content-row large-9 small-9 columns centered">			
			October 2012 - March 2013
		</div>		
	</div>		
</fieldset>	
</div>


@stop