@extends('layouts.main')
@section('content')

<h1>Portfolio</h1>

<div class="panel">
	<div class="row">
	<div class="panel callout radius large-4 small-4 centered columns">
		
		<ul>Table of contents
			<li>Education and training</li>
			<li>Work Experience</li>			
			<li>Skills and competences</li>
			<li>Others</li>
		</ul>
	</div>
	<div class="large-8 small-8 centered columns">
		<div class="panel callout radius">
			<div class="row">
				<div class="large-9 small-9 centered columns">
					<p>
						Hi!</br>
						My name is Carles, in this page you may find an overall of my
						past works as well as some of the new projects I am working on</li> 
					</p>
				</div>
				<div class="large-3 small-3 centered columns">
					<a href="https://www.linkedin.com/in/carsopre">
						{{HTML::image('assets/imgs/Linkedin-icon.png')}}
					</a>
				</div>
			</div>	
		</div>
	</div>
	</div>
</div>

<fieldset>
	<legend><h3>Final Project</h3></legend>		
	<div class="title-sec">
			Context-aware systems in well-being. From well-being domain to UML specification.</br>
			Final project done during a 10 month Erasmus-exchange program in Universiteit Twente (Netherlands).		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Background	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			SWELL-COMMIT research project
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			Topic	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			In this project is given a solution approach for generating UML models from the well-being domain generated by the SWELL committee.</br>
			This models aim to specify the context, activity and class diagrams of any given application within the well-being domain.
			Furthermore, a study of previous works Is done as well as a specification comparison with ConText toolkit.
			Finally the solution approach proposed is mapped with the SWELL global architecture and with a specific architecture of a SWELL partner, CommonSense.
		</div>		
	</div>
	<div class="row sec-subcategory">
		<div class="title-row large-3 small-3 columns centered">
			University	
		</div>
		<div class="content-row large-9 small-9 columns centered">
			Universiteit Twente (Netherlands)
		</div>		
	</div>
</fieldset>
<fieldset>
	<legend><h3>Carsopre-web</h3></legend>		
	
</fieldset>
<fieldset>
	<legend><h3>Project Management tool</h3></legend>		
	
</fieldset>


@stop